In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_excel('data_new.xlsx')
df

Month  WeekOfMonth  DayOfWeek     Make AccidentArea  DayOfWeekClaimed  \
0         12            5          3    Honda        Urban                 2   
1          1            3          3    Honda        Urban                 1   
2         10            5          5    Honda        Urban                 4   
3          6            2          6   Toyota        Rural                 5   
4          1            5          1    Honda        Urban                 2   
...      ...          ...        ...      ...          ...               ...   
15414     11            4          5   Toyota        Urban                 2   
15415     11            5          4  Pontiac        Urban                 5   
15416     11            5          4   Toyota        Rural                 5   
15417     12            1          1   Toyota        Urban                 4   
15418     12            2          3   Toyota        Urban                 4   

       MonthClaimed  WeekOfMonthClaimed     Sex MaritalStatus  ...  \
0                 1                   1  Female        Single  ...   
1                 1                   4    Male        Single  ...   
2                11                   2    Male       Married  ...   
3                 7                   1    Male       Married  ...   
4                 2                   2  Female        Single  ...   
...             ...                 ...     ...           ...  ...   
15414            11                   5    Male       Married  ...   
15415            12                   1    Male       Married  ...   
15416            12                   1    Male        Single  ...   
15417            12                   2  Female       Married  ...   
15418            12                   3    Male        Single  ...   

       WitnessPresent AgentType NumberOfSuppliments AddressChange_Claim  \
0                  No  External                none              1 year   
1                  No  External                none           no change   
2                  No  External                none           no change   
3                  No  External         more than 5           no change   
4                  No  External                none           no change   
...               ...       ...                 ...                 ...   
15414              No  External                none           no change   
15415              No  External         more than 5           no change   
15416              No  External              1 to 2           no change   
15417              No  External         more than 5           no change   
15418              No  External              1 to 2           no change   

      NumberOfCars  Year  BasePolicy       Date  DateClaimed  Date_Diff  
0           3 to 4  1994   Liability 1994-12-29   1994-01-05       -358  
1        1 vehicle  1994   Collision 1994-01-20   1994-01-25          5  
2        1 vehicle  1994   Collision 1994-10-29   1994-11-11         13  
3        1 vehicle  1994   Liability 1994-06-12   1994-07-02         20  
4        1 vehicle  1994   Collision 1994-02-01   1994-02-09          8  
...            ...   ...         ...        ...          ...        ...  
15414    1 vehicle  1996   Collision 1996-11-23   1996-12-04         11  
15415       3 to 4  1996   Liability 1996-11-29   1996-12-07          8  
15416    1 vehicle  1996   Collision 1996-11-29   1996-12-07          8  
15417    1 vehicle  1996  All Perils 1996-12-03   1996-12-13         10  
15418    1 vehicle  1996   Collision 1996-12-12   1996-12-20          8  

[15419 rows x 36 columns]

In [3]:
X = df[['AccidentArea',
        'Sex',
        'MaritalStatus',
        'Age', 
        'Fault', 
        'VehicleCategory', 
        'VehiclePrice', 
        'RepNumber', 
        'Deductible', 
        'DriverRating', 
        'Days_Policy_Accident',
        'Days_Policy_Claim',
        'PastNumberOfClaims',
        'AgeOfVehicle',
        'PoliceReportFiled',
        'WitnessPresent',
        'AgentType',
        'NumberOfSuppliments',
        'AddressChange_Claim',
        'NumberOfCars',
        'BasePolicy',
        'Date_Diff']]

    

y = df['FraudFound_P']

print(X.shape)
print(y.shape)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)


(15419, 22)
(15419,)
(12335, 22)
(3084, 22)
(12335,)
(3084,)


In [4]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder


categorical_columns =  ['AccidentArea',
                        'Sex',
                        'MaritalStatus',
                        'Fault', 
                        'VehicleCategory', 
                        'VehiclePrice',
                        'Days_Policy_Accident',
                        'Days_Policy_Claim',
                        'PastNumberOfClaims',
                        'AgeOfVehicle',
                        'PoliceReportFiled',
                        'WitnessPresent',
                        'AgentType',
                        'NumberOfSuppliments',
                        'AddressChange_Claim',
                        'NumberOfCars',
                        'BasePolicy']


preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(), categorical_columns)
    ],
    remainder='passthrough'  # This will keep non-categorical columns unchanged
)

# Step 4: Fit and transform X_train
X_train_encoded = preprocessor.fit_transform(X_train)

# Step 5: Transform X_test using the same transformer
X_test_encoded = preprocessor.transform(X_test)

print(X_train_encoded.shape)

(12335, 67)


d:\Anaconda\lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
d:\Anaconda\lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
d:\Anaconda\lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
d:\Anaconda\lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
d:\Anaconda\lib\site-packages\sklear

In [5]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

clf = RandomForestClassifier(random_state=0)
clf.fit(X_train_encoded, y_train)
y_pred_train = clf.predict(X_train_encoded)
y_pred = clf.predict(X_test_encoded)
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy of the Random Forest Classifier:", accuracy)

d:\Anaconda\lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
d:\Anaconda\lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):


Accuracy of the Random Forest Classifier: 0.9383916990920882


d:\Anaconda\lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
d:\Anaconda\lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):


In [6]:
from sklearn.model_selection import RandomizedSearchCV
clf2 = RandomForestClassifier(random_state=0)

param_dist = {
    "n_estimators": list(range(1, 1000)),
    "max_depth": list(range(1, 10)),
    "min_samples_split": list(range(5, 100))
}


random_search = RandomizedSearchCV(clf2, param_distributions=param_dist, n_iter=1000, cv=10, random_state=0, n_jobs=-1, scoring='recall')
random_search.fit(X_train_encoded, y_train)


best_params = random_search.best_params_
best_score = random_search.best_score_

print("Best Hyperparameters:", best_params)
print("Mean Cross-Validated Score of the Best Estimator:", best_score)

best_estimator = random_search.best_estimator_

y_pred2_train = best_estimator.predict(X_train_encoded)
y_pred2 = best_estimator.predict(X_test_encoded)
accuracy2 = accuracy_score(y_test, y_pred2)

print("Accuracy of the Random Forest Classifier (Tuned):", accuracy2)

d:\Anaconda\lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
d:\Anaconda\lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):


Best Hyperparameters: {'n_estimators': 2, 'min_samples_split': 16, 'max_depth': 7}
Mean Cross-Validated Score of the Best Estimator: 0.02317660125879304
Accuracy of the Random Forest Classifier (Tuned): 0.9396887159533074


d:\Anaconda\lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
d:\Anaconda\lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
d:\Anaconda\lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
d:\Anaconda\lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):


In [7]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score, confusion_matrix
accuracy_train_combined = accuracy_score(y_train, y_pred_train)
precision_train_combined = precision_score(y_train, y_pred_train)
recall_train_combined = recall_score(y_train, y_pred_train)
roc_auc_train_combined = roc_auc_score(y_train, clf.predict_proba(X_train_encoded)[:, 1])
confusion_matrix_train_combined = confusion_matrix(y_train, y_pred_train)

accuracy_test_combined = accuracy_score(y_test, y_pred)
precision_test_combined = precision_score(y_test, y_pred)
recall_test_combined = recall_score(y_test, y_pred)
roc_auc_test_combined = roc_auc_score(y_test, clf.predict_proba(X_test_encoded)[:, 1])
confusion_matrix_test_combined = confusion_matrix(y_test, y_pred)

print("Training Set Metrics (Not Tuned):")
print("Accuracy:", accuracy_train_combined)
print("Precision:", precision_train_combined)
print("Recall:", recall_train_combined)
print("ROC AUC:", roc_auc_train_combined)
print("Confusion Matrix:\n", confusion_matrix_train_combined)

print("\nTest Set Metrics (Not Tuned):")
print("Accuracy:", accuracy_test_combined)
print("Precision:", precision_test_combined)
print("Recall:", recall_test_combined)
print("ROC AUC:", roc_auc_test_combined)
print("Confusion Matrix:\n", confusion_matrix_test_combined)





d:\Anaconda\lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
d:\Anaconda\lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
d:\Anaconda\lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
d:\Anaconda\lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
d:\Anaconda\lib\site-packages\sklear

Training Set Metrics (Not Tuned):
Accuracy: 1.0
Precision: 1.0
Recall: 1.0
ROC AUC: 1.0
Confusion Matrix:
 [[11602     0]
 [    0   733]]

Test Set Metrics (Not Tuned):
Accuracy: 0.9383916990920882
Precision: 0.5
Recall: 0.015789473684210527
ROC AUC: 0.7983614010839122
Confusion Matrix:
 [[2891    3]
 [ 187    3]]


d:\Anaconda\lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
d:\Anaconda\lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
d:\Anaconda\lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
d:\Anaconda\lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
d:\Anaconda\lib\site-packages\sklear

In [8]:
accuracy_train_combined = accuracy_score(y_train, y_pred2_train)
precision_train_combined = precision_score(y_train, y_pred2_train)
recall_train_combined = recall_score(y_train, y_pred2_train)
roc_auc_train_combined = roc_auc_score(y_train, best_estimator.predict_proba(X_train_encoded)[:, 1])
confusion_matrix_train_combined = confusion_matrix(y_train, y_pred2_train)

accuracy_test_combined = accuracy_score(y_test, y_pred2)
precision_test_combined = precision_score(y_test, y_pred2)
recall_test_combined = recall_score(y_test, y_pred2)
roc_auc_test_combined = roc_auc_score(y_test, best_estimator.predict_proba(X_test_encoded)[:, 1])
confusion_matrix_test_combined = confusion_matrix(y_test, y_pred2)

print("Training Set Metrics (Tuned):")
print("Accuracy:", accuracy_train_combined)
print("Precision:", precision_train_combined)
print("Recall:", recall_train_combined)
print("ROC AUC:", roc_auc_train_combined)
print("Confusion Matrix:\n", confusion_matrix_train_combined)

print("\nTest Set Metrics (Tuned):")
print("Accuracy:", accuracy_test_combined)
print("Precision:", precision_test_combined)
print("Recall:", recall_test_combined)
print("ROC AUC:", roc_auc_test_combined)
print("Confusion Matrix:\n", confusion_matrix_test_combined)



Training Set Metrics (Tuned):
Accuracy: 0.942359140656668
Precision: 0.9583333333333334
Recall: 0.03137789904502047
ROC AUC: 0.8328095569917497
Confusion Matrix:
 [[11601     1]
 [  710    23]]

Test Set Metrics (Tuned):
Accuracy: 0.9396887159533074
Precision: 1.0
Recall: 0.021052631578947368
ROC AUC: 0.8119839595533409
Confusion Matrix:
 [[2894    0]
 [ 186    4]]


d:\Anaconda\lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
d:\Anaconda\lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
d:\Anaconda\lib\site-packages\sklearn\utils\validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
d:\Anaconda\lib\site-packages\sklearn\utils\validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
d:\Anaconda\lib\site-packages\sklear